import { z } from 'zod';
import { PUNCH_ACTIONS, PUNCH_TYPES } from './punch.interface.js';

/** Exactly four digits. Not a number — leading zeros are part of the code. */
const code = z
  .string()
  .regex(/^\d{4}$/, 'Enter your 4-digit code');

const slug = z.string().min(1);

/** Local wall-clock, because that is what a manager reads off a rota. */
const localDateTime = z
  .string()
  .regex(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/, 'Use the date and time picker');

const objectId = z.string().regex(/^[0-9a-fA-F]{24}$/, 'Not a valid id');

const lookup = z.object({
  body: z.object({ slug, code }),
});

const record = z.object({
  body: z.object({
    slug,
    code,
    action: z.enum(PUNCH_ACTIONS),
    /**
     * Generated by the client, once per tap. A retry of the same tap carries
     * the same key and is answered with the original punch instead of a second
     * one — which is what stops a double tap becoming a double punch.
     */
    idempotencyKey: z.string().min(8).max(100),
  }),
});

const managerCreate = z.object({
  body: z.object({
    userId: objectId,
    type: z.enum(PUNCH_TYPES),
    at: localDateTime,
  }),
});

const managerAmend = z.object({
  params: z.object({ id: objectId }),
  body: z.object({ at: localDateTime }),
});

const managerVoid = z.object({
  params: z.object({ id: objectId }),
});

export const punchValidation = {
  lookup,
  record,
  managerCreate,
  managerAmend,
  managerVoid,
};
